name: CI

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: src/package-lock.json
    
    - name: Install dependencies
      run: |
        cd src
        npm ci
    
    - name: Update version from git tags
      run: node scripts/version.js
    
    - name: Install global dependencies
      run: |
        npm install -g pkg
        sudo apt-get update
        sudo apt-get install -y upx-ucl libxml2-utils
    
    - name: Build project
      run: |
        cd src
        make prebuild
        make build-node
    
    - name: Run tests
      run: node test/test-runner.js
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results-node${{ matrix.node-version }}
        path: test-results/

  build-multiplatform:
    runs-on: ${{ matrix.os }}
    needs: test
    
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            targets: linux
          - os: macos-latest
            platform: macos
            targets: macos
          - os: windows-latest
            platform: windows
            targets: win64
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: src/package-lock.json
    
    - name: Install dependencies
      run: |
        cd src
        npm ci
    
    - name: Install global dependencies (Linux)
      if: matrix.platform == 'linux'
      run: |
        npm install -g pkg
        sudo apt-get update
        sudo apt-get install -y upx-ucl libxml2-utils
    
    - name: Install global dependencies (macOS)
      if: matrix.platform == 'macos'
      run: |
        npm install -g pkg
        brew install upx
    
    - name: Install global dependencies (Windows)
      if: matrix.platform == 'windows'
      run: |
        npm install -g pkg
        choco install upx
    
    - name: Update version from git tags
      run: node scripts/version.js
    
    - name: Build for ${{ matrix.platform }}
      run: |
        cd src
        make ${{ matrix.targets }}
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: svgop-${{ matrix.platform }}
        path: |
          bin/
          dist/
          !bin/**/.gitkeep
    
    - name: Run platform-specific tests
      run: node test/test-runner.js

  security-scan:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: src/package-lock.json
    
    - name: Install dependencies
      run: |
        cd src
        npm ci
    
    - name: Run security audit
      run: |
        cd src
        npm audit --audit-level=moderate
    
    - name: Run vulnerability scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'